name: Tag & Note Release

on:
  pull_request:
    branches: [ main ]
    types: [ closed ]

permissions:
  contents: write

concurrency:
  group: release-${{ github.event.pull_request.head.ref }}
  cancel-in-progress: false

jobs:
  release:
    if: >
      github.event.pull_request.merged == true &&
      startsWith(github.event.pull_request.head.ref, 'release/')
    runs-on: macos-15
    steps:
      - name: Extract version from branch
        id: v
        shell: bash
        run: |
          ref="${{ github.event.pull_request.head.ref }}"
          if [[ "$ref" =~ ^release/([0-9]+\.[0-9]+\.[0-9]+)$ ]]; then
            echo "version=${BASH_REMATCH[1]}" >> "$GITHUB_OUTPUT"
          else
            echo "Branch name must be release/x.y.z (got: $ref)" >&2
            exit 1
          fi
